### ISSUE TITLE
When trying to answer the call i am getting the open channel error

### ISSUE THREAD

**Issue by harish-chander** [babblevoice/babble-drachtio-callmanager#32]
i am trying to answer the call but i am getting the below error . Project RTP is install as well

```bash
449 |
450 |     if( !params.forcelocal && server.interface.get() ) {
451 |       return server.interface.get().openchannel( params, cb )
452 |     } else {
453 |       /* use local */
454 |       const chan =  actualprojectrtp.openchannel( params, ( d ) => {
                        ^
TypeError: undefined is not an object (evaluating 'actualprojectrtp.openchannel')
      at /home/zenit/drachtio-client/node_modules/@babblevoice/projectrtp/index.js:454:20
      at openchannel (/home/zenit/drachtio-client/node_modules/@babblevoice/projectrtp/index.js:441:21)
      at /home/zenit/drachtio-client/node_modules/@babblevoice/babble-drachtio-callmanager/lib/call.js:2606:34
      at #openrelatedchannel (/home/zenit/drachtio-client/node_modules/@babblevoice/babble-drachtio-callmanager/lib/call.js:2600:29)
      at /home/zenit/drachtio-client/node_modules/@babblevoice/babble-drachtio-callmanager/lib/call.js:1419:12
      at #openchannelsforanswer (/home/zenit/drachtio-client/node_modules/@babblevoice/babble-drachtio-callmanager/lib/call.js:1413:32)
      at /home/zenit/drachtio-client/node_modules/@babblevoice/babble-drachtio-callmanager/lib/call.js:1469:12
      at processTicksAndRejections (:55:76)
```

**Comment by tinpotnick** [comment]
Hi,

This will be to do with node including the binary for projectrtp. As part of an npm install, it should build projectrtp - but this may have failed because of requirements missing.

If you go into the projectrtp folder, and run npm run build - does it build ok - are there any requirements missing?

**Comment by tinpotnick** [comment]
Hi, hopefully this resolved your issue. I'll close it for now, as this issue has gone quiet.
